name: Deploy to Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - run: npm ci
      
      - name: Build
        run: npx vite build
      
      - name: Check build output
        run: |
          echo "Listing dist directory:"
          ls -la dist/
      
      - name: Deploy to Pages
        run: |
          echo "Deploying to /sites/${{ gitea.repository }}"
          
          # Create a temporary container with the sites volume mounted
          docker run --rm \
            -v gitea_sites:/sites \
            -v $(pwd)/dist:/source:ro \
            alpine sh -c "
              mkdir -p /sites/${{ gitea.repository }} && \
              cp -r /source/* /sites/${{ gitea.repository }}/ && \
              echo 'Files copied to volume:' && \
              ls -la /sites/${{ gitea.repository }}/
            "
          
          echo "✅ Deployed!"
