name: Deploy to Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - run: npm ci
      
      - name: Build
        run: npx vite build
      
      - name: Check build output
        run: |
          echo "Listing dist directory:"
          ls -la dist/
      
      - name: Deploy to Pages
        run: |
          echo "Deploying to gitea_sites volume at ${{ gitea.repository }}"
          cd dist
          tar -czf - . | docker run --rm -i \
            --network gitea_gitea \
            -v gitea_sites:/sites \
            alpine sh -c "mkdir -p /sites/${{ gitea.repository }} && tar -xzf - -C /sites/${{ gitea.repository }} && echo '✅ Deployed!' && ls -la /sites/${{ gitea.repository }}/"
